name: Continuos Integration

# a palavra chave "on" recebe o evento que ira disparar o workflow
# da pipeline
on: [pull_request, push]  #Também é possivel especificar mais ainda o processo. Por Ex.:
                              #on:
                                 #pull_request:
                                    #branches:
                                      #['main'] #apenas na branche "main" sera executado o workflow

#são os passo a passo do workflow
jobs:
  continuos-integration: # <= job
    runs-on: ubuntu-latest # especifica o ambiente em que o workflow ira executar

    steps:
      - uses: action/checout@v4 #clona o repositorio para maquina virtual do githubactions
      - name: Using node.js
        uses: actions/setup-node@v2 #instala o node
        with: #defini variaveis dentro do actions
          node-version: 22.x
      - name: run install, test and build
        run: |
          npm install
          npm run test
          npm run build
      
